language: node_js
node_js:
    - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - echo $FIREBASE_CONFIG > config.ts

script:
  - ng build --prod --aot

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
